package com.jagoinc.jagopos;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jago
 */
public class CustomerCard extends javax.swing.JFrame {
    private Customer customer;
    private boolean _updateFlag;
    private ResultSet _updateSet;
    /**
     * Creates new form CustomerCard
     * @throws java.sql.SQLException
     */
    public CustomerCard() throws SQLException {
        _updateFlag = false;
        customer = new Customer();
        initComponents();
        this.setTitle("New Customer");
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }
    
    public CustomerCard(boolean updateFlag){
        _updateFlag = updateFlag;
        initComponents();
        this.setTitle("Customer Detail");
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }
    
    public CustomerCard(Customer customer, boolean creatingNewCustomer){
        _updateFlag = false;
        initComponents();
        customerNameTextField.setText(customer.getName());
        customerPostalCodeTextField.setText(customer.getPostalCode());
        customerEmailAddressTextField.setText(customer.getEmail());
        customerPhoneNumberTextField.setText(customer.getPhone());
        String customerID = String.valueOf(customer.getCustomerID());
        customerIDTextLabel.setText(customerID);
        
        if(creatingNewCustomer){
            customerHeadingTextLabel.setText("New Unsaved Customer");
            customerDeleteButton.setEnabled(false);
        }else{
            customerHeadingTextLabel.setText("Customer");
        }
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerHeadingTextLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerIDTextLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerPostalCodeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        customerPhoneNumberTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        customerEmailAddressTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        customerDialogSaveAndCloseButton = new javax.swing.JButton();
        customerDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("New Customer Card"); // NOI18N
        setResizable(false);

        customerHeadingTextLabel.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        customerHeadingTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerHeadingTextLabel.setText("Customer Info");

        jLabel2.setText("Customer ID:");

        customerIDTextLabel.setText("1");

        jLabel4.setText("Customer Name:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Customer ID is unique and cannot be changed.");

        jLabel6.setText("Postal Code:");

        jLabel7.setText("Phone Number:");

        customerPhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerPhoneNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("E-Mail Address:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        customerDialogSaveAndCloseButton.setText("Save & Close");
        customerDialogSaveAndCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDialogSaveAndCloseButtonActionPerformed(evt);
            }
        });

        customerDeleteButton.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerHeadingTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerIDTextLabel)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(customerNameTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerPostalCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerPhoneNumberTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerEmailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerDeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerDialogSaveAndCloseButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customerHeadingTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerIDTextLabel)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerPhoneNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(customerPostalCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(customerEmailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(customerDialogSaveAndCloseButton)
                    .addComponent(customerDeleteButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerPhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerPhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPhoneNumberTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerDialogSaveAndCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDialogSaveAndCloseButtonActionPerformed
        if(_updateFlag){
            try {
                populateandUpdateResultSet();
            } catch (SQLException ex) {
                Logger.getLogger(ProductCard.class.getName()).log(Level.SEVERE, null, ex);
                System.exit(80085);
            }
            this.dispose();
            return;
        }
        Customer customer = null;
        try {
            customer = new Customer();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerCard.class.getName()).log(Level.SEVERE, null, ex);
        }
        String escapedDescription = "";
        
        if(customerNameTextField.getText().contains("'")){
            escapedDescription = customerNameTextField.getText().replace("'", "\\'");
        }else{
            escapedDescription = customerNameTextField.getText();
        }
        if(customerEmailAddressTextField.getText().length() > 0){
            if(customerEmailAddressTextField.getText().contains("@") && customerEmailAddressTextField.getText().contains(".")){
                customer.setEmail(customerEmailAddressTextField.getText());
            }else{
                JOptionPane.showMessageDialog(this, "Please make sure your e-mail is valid.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        customer.setName(escapedDescription);
        customer.setPostalCode(customerPostalCodeTextField.getText());
        customer.setPhone(customerPhoneNumberTextField.getText());
        
        try {
            if(customer.saveCustomer()){
                this.dispose();
            }
        } catch (SQLException ex) {
            System.out.println("Error was caught:");
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_customerDialogSaveAndCloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new CustomerCard().setVisible(true);
                }catch(SQLException e){
                    
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerDeleteButton;
    private javax.swing.JButton customerDialogSaveAndCloseButton;
    private javax.swing.JTextField customerEmailAddressTextField;
    private javax.swing.JLabel customerHeadingTextLabel;
    private javax.swing.JLabel customerIDTextLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField customerPhoneNumberTextField;
    private javax.swing.JTextField customerPostalCodeTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    public void populateCard(ResultSet customer) throws SQLException {
        customerIDTextLabel.setText(customer.getString(1));
        customerPostalCodeTextField.setText(customer.getString(2));
        customerNameTextField.setText(customer.getString(3));
        customerPhoneNumberTextField.setText(customer.getString(4));
        customerEmailAddressTextField.setText(customer.getString(5));
        _updateSet = customer;
    }
    private void populateandUpdateResultSet() throws SQLException{
        
        _updateSet.updateString(2, customerPostalCodeTextField.getText());
        _updateSet.updateString(3, customerNameTextField.getText());
        _updateSet.updateString(4, customerPhoneNumberTextField.getText());
        _updateSet.updateString(5, customerEmailAddressTextField.getText());
        _updateSet.updateRow();
    }
    
    public void setHeaderText(String newHeaderText){
        customerHeadingTextLabel.setText(newHeaderText);
    }
}
