package com.jagoinc.jagopos;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jago
 */
public class ProductCard extends javax.swing.JFrame {
    private Product _product;
    private boolean _updateFlag;
    private ResultSet _updateSet;
    /**
     * Creates new form ProductCard
     */
    public ProductCard() {
        _updateFlag = false;
        _product = new Product();
        initComponents();
        this.setTitle("New Product");
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }
    
    public ProductCard(boolean updateFlag) {
        _updateFlag = updateFlag;
        initComponents();
        this.setTitle("Product Detail");
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productWindowHeaderTextLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productUPCTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inventoryTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        costTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        salePriceTextField = new javax.swing.JTextField();
        saveProductButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productWindowHeaderTextLabel.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        productWindowHeaderTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productWindowHeaderTextLabel.setText("Product Info");

        jLabel2.setText("Product Name:");

        jLabel3.setText("Product UPC:");

        productUPCTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUPCTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("UPC Must be Unique");

        jLabel5.setText("Current Inventory:");

        inventoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("@ Cost:");

        jLabel7.setText("Sale Price:");

        salePriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salePriceTextFieldActionPerformed(evt);
            }
        });

        saveProductButton.setText("Save & Close");
        saveProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productWindowHeaderTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(productNameTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(productUPCTextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inventoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveProductButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productWindowHeaderTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productUPCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(costTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salePriceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inventoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveProductButton)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productUPCTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUPCTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productUPCTextFieldActionPerformed

    private void inventoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryTextFieldActionPerformed

    private void salePriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salePriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salePriceTextFieldActionPerformed

    private void saveProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductButtonActionPerformed
        
        if(_updateFlag){
            try {
                populateandUpdateResultSet();
            } catch (SQLException ex) {
                Logger.getLogger(ProductCard.class.getName()).log(Level.SEVERE, null, ex);
                System.exit(80085);
            }
            this.dispose();
            return;
        }
        //check for UPC uniqueness and presence here eventually
        
        long UPC = 0;
        int inventory = 0;
        double cost = 0, salePrice = 0;
        String escapedDescription = "";
        
        if(productUPCTextField.getText().length() == 0 ){
            JOptionPane.showMessageDialog(this, "A UPC is required. Please enter UPC.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            UPC = Long.parseLong(productUPCTextField.getText());
        }
        if(inventoryTextField.getText().length() == 0 ){
        }else{
            inventory = Integer.parseInt(inventoryTextField.getText());
        }
        if(costTextField.getText().length() == 0 ){
        }else{
            cost = Double.parseDouble(costTextField.getText());
        }
        if(salePriceTextField.getText().length() == 0 ){
        }else{
            salePrice = Double.parseDouble(salePriceTextField.getText());
        }
        
        if(productNameTextField.getText().contains("'")){
            escapedDescription = productNameTextField.getText().replace("'", "\\'");
        }else{
            escapedDescription = productNameTextField.getText();
        }
        
        _product.setUPC(UPC);
        _product.setDescription(escapedDescription);
        _product.setInventory(inventory);
        _product.setCost(cost);
        _product.setPrice(salePrice);
        
        try {
            if(_product.saveProduct()){
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "That Product UPC is already in use. Please choose another.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println("Error was caught:");
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_saveProductButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costTextField;
    private javax.swing.JTextField inventoryTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JTextField productUPCTextField;
    private javax.swing.JLabel productWindowHeaderTextLabel;
    private javax.swing.JTextField salePriceTextField;
    private javax.swing.JButton saveProductButton;
    // End of variables declaration//GEN-END:variables

    public void populateCard(ResultSet product) throws SQLException{
        
        productUPCTextField.setText(product.getString(1));
        productNameTextField.setText(product.getString(2));
        costTextField.setText(product.getString(3));
        salePriceTextField.setText(product.getString(4));
        inventoryTextField.setText(product.getString(5));
        _updateSet = product;
    }
    
    private void populateandUpdateResultSet() throws SQLException{
        
        _updateSet.updateLong(1, Long.parseLong(productUPCTextField.getText()));
        _updateSet.updateString(2, productNameTextField.getText());
        _updateSet.updateString(3, costTextField.getText());
        _updateSet.updateString(4, salePriceTextField.getText());
        _updateSet.updateString(5, inventoryTextField.getText());
        _updateSet.updateRow();
    }
    
    public void setHeaderText(String newHeaderText){
        productWindowHeaderTextLabel.setText(newHeaderText);
    }
}
