package com.jagoinc.jagopos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.IOException;
import java.sql.SQLException;
/**
 *
 * @author jago
 */
public class SettingsPanel extends javax.swing.JFrame {

    private Session _settingsSession;
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() throws IOException, ClassNotFoundException{
        
        this._settingsSession = new Session();
        
        initComponents();
        this.setTitle("Settings");
        fillInSettings();
        
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currencyButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        settingsBusinessNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        settingsBusinessAddressTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        settingsBusinessPhoneTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        settingsBusinessEmailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        settingsBusinessWebsiteTextField = new javax.swing.JTextField();
        settingsSaveChangesButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        $CurrencyRadio = new javax.swing.JRadioButton();
        €CurrencyRadio = new javax.swing.JRadioButton();
        £CurrencyRadio = new javax.swing.JRadioButton();
        ¥CurrencyRadio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        settingsTaxRateTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        settingsTaxNameTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jago POS Settings");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("<html><u>Business Information:</u></html>");

        jLabel3.setText("Business Name:");

        settingsBusinessNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBusinessNameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Business Address:");

        settingsBusinessAddressTextArea.setColumns(15);
        settingsBusinessAddressTextArea.setLineWrap(true);
        settingsBusinessAddressTextArea.setRows(4);
        jScrollPane1.setViewportView(settingsBusinessAddressTextArea);

        jLabel5.setText("Business Phone:");

        jLabel6.setText("Business E-mail:");

        settingsBusinessEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBusinessEmailTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Business Website:");

        settingsSaveChangesButton.setText("Save Changes & Close");
        settingsSaveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsSaveChangesButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("<html><u>Currency:</u><html>");

        currencyButtonGroup.add($CurrencyRadio);
        $CurrencyRadio.setText("USD $");
        $CurrencyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                $CurrencyRadioActionPerformed(evt);
            }
        });

        currencyButtonGroup.add(€CurrencyRadio);
        €CurrencyRadio.setText("EUR €");
        €CurrencyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                €CurrencyRadioActionPerformed(evt);
            }
        });

        currencyButtonGroup.add(£CurrencyRadio);
        £CurrencyRadio.setText("GBP £");
        £CurrencyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                £CurrencyRadioActionPerformed(evt);
            }
        });

        currencyButtonGroup.add(¥CurrencyRadio);
        ¥CurrencyRadio.setText("JPY ¥");
        ¥CurrencyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ¥CurrencyRadioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("<html><u>Tax:</u></html>");

        jLabel10.setText("Sales Tax Rate (%):");

        jLabel11.setText("Tax Name: ");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel12.setText("(e.g. \"CA Sales Tax\")");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(settingsBusinessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent($CurrencyRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(€CurrencyRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(£CurrencyRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(¥CurrencyRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(settingsBusinessPhoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(settingsBusinessEmailTextField)
                                    .addComponent(settingsBusinessWebsiteTextField))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(settingsTaxNameTextField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                                .addComponent(settingsSaveChangesButton))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(settingsTaxRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(settingsBusinessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent($CurrencyRadio)
                    .addComponent(€CurrencyRadio)
                    .addComponent(£CurrencyRadio)
                    .addComponent(¥CurrencyRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsBusinessPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsTaxRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsTaxNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settingsBusinessEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsBusinessWebsiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsSaveChangesButton)
                            .addComponent(jButton1))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsBusinessEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBusinessEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsBusinessEmailTextFieldActionPerformed

    private void settingsSaveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsSaveChangesButtonActionPerformed
        
        _settingsSession.setName(settingsBusinessNameTextField.getText());
        _settingsSession.setAddress(settingsBusinessAddressTextArea.getText());
        _settingsSession.setEmail(settingsBusinessEmailTextField.getText());
        _settingsSession.setWebsite(settingsBusinessWebsiteTextField.getText());
        _settingsSession.setPhone(settingsBusinessPhoneTextField.getText());
        double holder = Double.parseDouble(settingsTaxRateTextField.getText());
        _settingsSession.setTaxRate(holder);
        _settingsSession.setTaxName(settingsTaxNameTextField.getText());
        
        try{
            _settingsSession.saveSettings();
        }catch(IOException e){
            System.out.println(e.getMessage());
            //System.exit(0);
        }catch(SQLException e){
            System.out.println(e.getMessage());
            //System.exit(0);
        }
        this.dispose();
        
    }//GEN-LAST:event_settingsSaveChangesButtonActionPerformed

    private void settingsBusinessNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBusinessNameTextFieldActionPerformed
        //this.setText(_settingsSession.getName());
    }//GEN-LAST:event_settingsBusinessNameTextFieldActionPerformed

    private void $CurrencyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_$CurrencyRadioActionPerformed
        _settingsSession.setCurrency('$');
        System.out.println(_settingsSession.getCurrency());
    }//GEN-LAST:event_$CurrencyRadioActionPerformed

    private void €CurrencyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_€CurrencyRadioActionPerformed
        _settingsSession.setCurrency('€');
        System.out.println(_settingsSession.getCurrency());
    }//GEN-LAST:event_€CurrencyRadioActionPerformed

    private void £CurrencyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_£CurrencyRadioActionPerformed
        _settingsSession.setCurrency('£');
        System.out.println(_settingsSession.getCurrency());
    }//GEN-LAST:event_£CurrencyRadioActionPerformed

    private void ¥CurrencyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_¥CurrencyRadioActionPerformed
        _settingsSession.setCurrency('¥');
        System.out.println(_settingsSession.getCurrency());
    }//GEN-LAST:event_¥CurrencyRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void fillInSettings(){
        settingsBusinessNameTextField.setText(_settingsSession.getName());
        settingsBusinessAddressTextArea.setText(_settingsSession.getAddress());
        settingsBusinessEmailTextField.setText(_settingsSession.getEmail());
        settingsBusinessWebsiteTextField.setText(_settingsSession.getWebsite());
        settingsBusinessPhoneTextField.setText(_settingsSession.getPhone());
        
        String holder = Double.toString(_settingsSession.getTaxRate());
        
        settingsTaxRateTextField.setText(holder);
        settingsTaxNameTextField.setText(_settingsSession.getTaxName());
        
        switch(_settingsSession.getCurrency()){
            case 0:
                currencyButtonGroup.setSelected($CurrencyRadio.getModel(), true);
                break;
            case 1:
                currencyButtonGroup.setSelected(€CurrencyRadio.getModel(), true);
                break;
            case 2:
                currencyButtonGroup.setSelected(£CurrencyRadio.getModel(), true);
                break;
            case 3:
                currencyButtonGroup.setSelected(¥CurrencyRadio.getModel(), true);
                break;
                
            default:
                currencyButtonGroup.setSelected($CurrencyRadio.getModel(), true);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                try{
                    
                    new SettingsPanel().setVisible(true);
                    
                }catch(IOException e){
                    
                    System.out.println("Settings File Failed to open. Aborting.");
                    System.exit(420);
                    
                }catch(ClassNotFoundException e){
                    System.out.println("Settings File Failed to open. Aborting.");
                    System.exit(421);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton $CurrencyRadio;
    private javax.swing.ButtonGroup currencyButtonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea settingsBusinessAddressTextArea;
    private javax.swing.JTextField settingsBusinessEmailTextField;
    private javax.swing.JTextField settingsBusinessNameTextField;
    private javax.swing.JTextField settingsBusinessPhoneTextField;
    private javax.swing.JTextField settingsBusinessWebsiteTextField;
    private javax.swing.JButton settingsSaveChangesButton;
    private javax.swing.JTextField settingsTaxNameTextField;
    private javax.swing.JTextField settingsTaxRateTextField;
    private javax.swing.JRadioButton £CurrencyRadio;
    private javax.swing.JRadioButton ¥CurrencyRadio;
    private javax.swing.JRadioButton €CurrencyRadio;
    // End of variables declaration//GEN-END:variables
}
